# Notes before starting:
#
# Set up /etc/ansible/hosts to include any hosts for which you want to
# run this playbook, within a `[mediawiki]` group.  Test that you can
# ping these hosts with ansible and the desired user.  If they are not
# already in known_hosts, you may get an error.  Either add them to
# known_hosts or edit the configuration to ignore that check.  See
# https://docs.ansible.com/ansible/latest/user_guide/intro_getting_started.html
# for general help with Ansible.

---
- hosts: mediawiki
  remote_user: root
  tasks:
  - name: install prerequisites
    # See https://www.mediawiki.org/wiki/Manual:Installation_requirements
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - apache2
      - curl
      - php
      - php-apcu
      - php-intl
      - php7.3-mbstring
      - php7.3-xml
      - postgresql
      - python-psycopg2

  - name: Create "wiki" user
    user:
      name: wiki
      shell: /bin/bash
      create_home: yes
      state: present

  - name: Download MediaWiki
    get_url:
      url: https://releases.wikimedia.org/mediawiki/1.31/mediawiki-1.31.1.tar.gz
      dest: /home/wiki/mediawiki-1.31.1.tar.gz
      owner: wiki
      group: wiki
      checksum: sha256:ce5ad8a07c8ef6832448629d8bb56a19b2f73632ddde29b5af2c08192943a48f

  - name: Extract MediaWiki tarball
    unarchive:
      src: /home/wiki/mediawiki-1.31.1.tar.gz
      dest: /home/wiki
      remote_src: yes
      owner: wiki
      group: wiki

  - name: Symlink to webserver directory
    file:
      state: link
      owner: www-data
      group: www-data
      src: /home/wiki/mediawiki-1.31.1
      path: /var/www/mediawiki

  - name: Create database user
    become: true
    become_user: postgres
    postgresql_user:
      name: wikiuser
      state: present
      password: "{{ __FILL_FROM_VAULT__ }}"
      encrypted: yes

  - name: Create database
    become: true
    become_user: postgres
    postgresql_db:
      name: wikidb
      owner: wikiuser

  - name: Enable PHP modules
    shell: phpenmod mbstring xml

  - name: Run install script
    # See https://www.mediawiki.org/wiki/Manual:Install.php#Script_specific_parameters
    become: true
    become_user: wiki
    shell: php /home/wiki/mediawiki-1.31.1/maintenance/install.php
    args:
      dbname: wikidb
      dbuser: wikiuser
      dbpass: "{{ __FILL_FROM_VAULT__ }}"
      dbtype: postgres
      pass: admin
      admin: admin
