# Notes before starting:
#
# Set up /etc/ansible/hosts to include any hosts for which you want to
# run this playbook, within a `[mediawiki]` group.  Test that you can
# ping these hosts with ansible and the desired user.  If they are not
# already in known_hosts, you may get an error.  Either add them to
# known_hosts or edit the configuration to ignore that check.  See
# https://docs.ansible.com/ansible/latest/user_guide/intro_getting_started.html
# for general help with Ansible.

---
- hosts: mediawiki
  remote_user: root
  tasks:
  - name: install prerequisites
    # See https://www.mediawiki.org/wiki/Manual:Installation_requirements
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - apache2
      - curl
      - mariadb-server
      - php
      - php-apcu
      - php-intl

  - name: Create "wiki" user
    user:
      name: wiki
      shell: /bin/bash
      create_home: yes
      state: present

  - name: Download MediaWiki
    get_url:
      url: https://releases.wikimedia.org/mediawiki/1.31/mediawiki-1.31.1.tar.gz
      dest: /home/wiki/mediawiki-1.31.1.tar.gz
      owner: wiki
      group: wiki
      checksum: sha256:ce5ad8a07c8ef6832448629d8bb56a19b2f73632ddde29b5af2c08192943a48f
